### ISSUE TITLE
Readme and Documentation? 

### ISSUE THREAD

**Issue by sarmel** [scalexm/trade-rs#4]

**Comment by scalexm** [comment]
I updated `README.md` in 133dcbef7a11b6627734ccec5b055032095b5c43.

**Comment by sarmel** [comment]
Thanks. Will be nice to have a params.example.json and keys.example.json files

**Comment by sarmel** [comment]
Is this project an equivalent of ccxt for rust?

**Comment by scalexm** [comment]
Kind of, although less ambitious. I’m writing this for my own use, so it will mainly be driven by my personal needs.
